### ISSUE TITLE
Classpath not read from environment

### ISSUE THREAD

**Issue by edudobay** [tcalmant/jpype-py3#14]
When starting the JVM, the `CLASSPATH` environment variable is not read to determine the VM's class path (I have to do it myself). Is this indeed the intended behaviour?

**Comment by zhuzhutest** [comment]
My environment is the MAC system. Each time you start the Java virtual machine will remind me: error = dlopen (/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Libraries/libjvm.dylib 9): no suitable image found. Did:

**Comment by tcalmant** [comment]
This project is now deprecated. Please use [jpype-project/jpype](https://github.com/jpype-project/jpype) instead.
