### ISSUE TITLE
JVM apparently forgets CLASS_PATH inbetween queries

### ISSUE THREAD

**Issue by nutztherookie** [tcalmant/jpype-py3#16]
This is a little hard to explain, but I'll do my best:
Setup: Django, with [Informix-Django-ORM-Layer](https://github.com/nutztherookie/django-informix) atop [JayDeBeApi3](https://github.com/nutztherookie/JayDeBeApi3) atop jpype-py3.
A lot is working pretty well so far, but now I bumped into the following problem:

The function [_jdbc_connect_jpype](https://github.com/nutztherookie/JayDeBeApi3/blob/master/src/jaydebeapi/__init__.py#L84) initially creates the JVM with '-Djava.class.path=path/to/ifxjdbc.jar', attaches the Thread, selects (or registers?) the Class ('com.informix.jdbc.IfxDriver') and gets the  connection [__init__.py#L117](https://github.com/nutztherookie/JayDeBeApi3/blob/master/src/jaydebeapi/__init__.py#L117)

This works great up to that point where the function is called again, finds an existing JVM, and tries to get the connection again. It crashes and tells me:
`No suitable driver found for jdbc:informix-sqli://<dbname> etc../`
which sounds like it forgot the CLASSPATH variable, somehow.

I've been trying to debug this for the last half a day. Any help would be highly appreciated!

**Comment by tcalmant** [comment]
I don't use JDBC, so I have not tried to use JayDeBe (yet).
Initially, I thought about a ClassLoader problem, but the call of ``JClass()`` shouldn't work in that case.

It might be a detail, but I see that in Jython, the driver class is loaded and instantiated ([line 56](https://github.com/nutztherookie/JayDeBeApi3/blob/master/src/jaydebeapi/__init__.py#L56)), whereas in jpype, the class is only loaded ([line 116](https://github.com/nutztherookie/JayDeBeApi3/blob/master/src/jaydebeapi/__init__.py#L116)).

Have you tried printing out the ``id()`` of the class loaded line 116 ?
If the Python ID is the same, then JPype uses the class it loaded on the first, else the class might have been garbage collected.

**Comment by nutztherookie** [comment]
Thank you for your reply!

newInstance() is not available on the jpype.JClass(jclassname), and weirdly it works initially =(

The other idea with `id()` yielded the same ID.

I've forked JayDeBeApi from the initial project, so I don't have a lot of experience with Java-Python-interaction. I'm not even sure how to debug or what I can expect to work or not to work.
e.g.: 
`dir(jpype.JClass(jclassname))` tells me that it has the method "getClass()", yet, when I try to call it:
`No matching overloads found. at native/common/jp_method.cpp:121`

Is there maybe a deeper, underlying problem here?

**Comment by tcalmant** [comment]
The equivalent of the ``newInstance()`` call would be ``jpype.JClass(jclassname)()``.
Maybe the driver does some registration in its constructor... According to the JDBC doc I've read that shouldn't be the case, but I'd prefer to have the exact same behaviour between Jython and JPype.

The fact that you get the same Python id() means that the class has been correctly loaded and kept by the same class loader, so we don't have class checksum conflicts.

I've seen that ``getClass()`` doesn't work on class objects (same as in the original JPype), but I don't know if it's possible to get a hand on the "real" Class type from JNI.

**Comment by nutztherookie** [comment]
jpype.JClass(jclassname)() didn't help =(

I'll try some more debugging in a bit. Altough I don't really know how to proceed anymore.

**Comment by tcalmant** [comment]
What I would do:
1. Write a pure-java app executing the exact same calls as through jpype; check the result
2. Call this Java class through JPype; check the result
3. Rewrite the same code as in step 1, in pure jpype; check in single-thread mode and multi-thread
4. Compare with the current code

**Comment by nutztherookie** [comment]
Thanks for your pointers. How would I go about simulating the whole JVM-Instanciating to begin with?

**Comment by nutztherookie** [comment]
So in the end, I actually replaced jpype with py4j. It appeared to be way more complex due to the reputed extra Java code, but it's actually possible to write the Java stuff in Python and just spawn a vanilla JVM there as well.

Thank you very much for your help anyways!
