### ISSUE TITLE
RuntimeError: No Java/JDK could be found. I looked in the following directories:

### ISSUE THREAD

**Issue by pkuong** [tcalmant/jpype-py3#17]
Even though /usr/lib/jvm/java-1.7.0-openjdk-amd64/ exist and $JAVA_HOME is set to point to that, I got the following error:

RuntimeError: No Java/JDK could be found. I looked in the following directories:

/usr/lib/jvm/java-1.7.0-openjdk-amd64/

/usr/lib/jvm/java-1.7.0-openjdk-amd64

/usr/lib/jvm/java-7-openjdk-amd64

The system is ubuntu precise 64.

**Comment by tcalmant** [comment]
JPype looks for the *libjvm.so* file, which should be in ``/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so``
Could you check if it is present ?

**Comment by pkuong** [comment]
yes, that exists. Still no luck.

/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/amd64/server/libjvm.so

**Comment by pkuong** [comment]
Hi, I realized that my system couldn't find javac.. after I reinstalled java, it works. Closing this now.. Thanks.
