### ISSUE TITLE
Question: How to pass null to Java ?

### ISSUE THREAD

**Issue by arita291** [tcalmant/jpype-py3#21]
Hi,
1)
I would like to pass null as argument to a Java method from JPype

2) How can we casting of Class in JPype:

txt= u'test'
reader = jp.JClass('java.io.StringReader')(txt)

**Comment by marscher** [comment]
Am 27.03.2016 um 01:12 schrieb arita291:
> Hi,
>
> I would like to pass null as argument to a Java method.
> How can I do this ?
> Spent quite a lot of time to search...
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tcalmant/jpype-py3/issues/21>
>
try None

**Comment by arita291** [comment]
Hello,
It worked now.
Problem was with one class having private constructor
and one need to use public method to get initialization...

Thank you
Kind regards
KN
