### ISSUE TITLE
Restrictions on pathnames for JDK installations

### ISSUE THREAD

**Issue by rolweber** [tcalmant/jpype-py3#24]
I was trying to install jpype-py3 (as a prerequisite of brunel) via pip into an Anaconda environment. That environment has the Anaconda OpenJDK package installed. The base directory of the environment, and therefore of the OpenJDK, is `/opt/conda/envs/python3`. Afaict, it contains all the files that JPype would require. I'm pointing JAVA_HOME there, yet JPype says that it cannot find a JDK.

The JDK finder has a hardcoded list of directory names it will accept, and my Anaconda environment path doesn't match.
https://github.com/tcalmant/jpype-py3/blob/ca6fc96a76d430c753b56ec2a4ed2a3eced0dac3/setup.py#L143
Additionally, the JDK finder calls `realpath`, so that I cannot symlink around this restriction.
https://github.com/tcalmant/jpype-py3/blob/ca6fc96a76d430c753b56ec2a4ed2a3eced0dac3/setup.py#L146

Is there a way to tell JPype that the JDK _really_ is where I'm pointing JAVA_HOME at, and that it should skip the pathname check?

**Comment by rolweber** [comment]
There is an Anaconda package for JPype with a slightly different name on conda-forge, but the brunel package explicitly depends on jpype-py3.

Giving the Anaconda environment a name that includes "jdk" might work around the check. But I'm looking for a way to install brunel while still being able to choose arbitrary environment names.

**Comment by tcalmant** [comment]
Hi,
The call to ``realpath()`` was added to avoid ``isdir()`` to return False when using a symbolic link to the JDK.
A solution would be to replace [this check](https://github.com/tcalmant/jpype-py3/blob/ca6fc96a76d430c753b56ec2a4ed2a3eced0dac3/setup.py#L145-L148) by the following snippet:

```python
    # Construct the full path
    if not os.path.isdir(os.path.realpath(java_home)):
        return
```

Another solution would be to handle a new environment variable, either ``JPYPE_JAVA_HOME`` or ``JPYPE_NO_CHECK`` to disable this behaviour.

**Comment by rolweber** [comment]
Changing the check would enable a symlink workaround, but not address the underlying problem. Therefore, a new env variable sounds like the better solution to me.
Do you actually need the isdir check? A few lines below, you verify that there's a subdir `include`. Doesn't that imply that the parent is a directory?

Another idea: pass a boolean parameter to [`check_jdk`](https://github.com/tcalmant/jpype-py3/blob/ca6fc96a76d430c753b56ec2a4ed2a3eced0dac3/setup.py#L132) that enables/disables the check for the directory name. When checking for the path from JAVA_HOME, ignore the directory name. When guessing paths based on other information, like the Windows registry or platform defaults, consider the directory name as well.

**Comment by tcalmant** [comment]
> Do you actually need the isdir check?

It was added due to a bug on an exotic setup when I started working on this fork (bad resolution of symlinks IIRC).
It might be possible to remove it now.

> A few lines below, you verify that there's a subdir include. Doesn't that imply that the parent is a directory?

This (kind of) ensures that we have a JDK, behind a symlink or not.
In general cases, it is sufficient for the setup script.

> Another idea: pass a boolean parameter to check_jdk that enables/disables the check for the directory name. When checking for the path from JAVA_HOME, ignore the directory name. When guessing paths based on other information, like the Windows registry or platform defaults, consider the directory name as well.

Your idea of having a flag indicating if the path can be trusted as is seems OK to me.
This only requires [check_homes()](https://github.com/tcalmant/jpype-py3/blob/ca6fc96a76d430c753b56ec2a4ed2a3eced0dac3/setup.py#L119) to accept a dictionary associating a boolean to each entry, which can be done easily.

**Comment by rolweber** [comment]
Thanks!
