### ISSUE TITLE
No Java/JDK could be found.

### ISSUE THREAD

**Issue by chrisspen** [tcalmant/jpype-py3#26]
Installing Jpype1-py3 incorrectly reports that there's no JDK found.

    $ pip install jpype1-py3
    Collecting jpype1-py3
      Downloading JPype1-py3-0.5.5.2.tar.gz (87kB)
        100% |████████████████████████████████| 92kB 1.3MB/s 
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "/tmp/pip-build-cxoimb4p/jpype1-py3/setup.py", line 454, in <module>
            config = LinuxJDKFinder()
          File "/tmp/pip-build-cxoimb4p/jpype1-py3/setup.py", line 402, in __init__
            java_home = self.find_jdk_home()
          File "/tmp/pip-build-cxoimb4p/jpype1-py3/setup.py", line 442, in find_jdk_home
            raise NoJDKError(visited_folders)
        __main__.NoJDKError: No JDK found
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "<string>", line 1, in <module>
          File "/tmp/pip-build-cxoimb4p/jpype1-py3/setup.py", line 468, in <module>
            .format('\n'.join(ex.possible_homes)))
        RuntimeError: No Java/JDK could be found. I looked in the following directories:
        
        /usr/lib/jvm/default-java
        /usr/lib/jvm/java-8-openjdk-amd64
        /usr/lib/jvm/default-java
        /usr/lib/jvm/java-1.8.0-openjdk-amd64
        
        Please check that you have it installed.
        
        If you have and the destination is not in the above list, please find out where your java's home is, set your JAVA_HOME environment variable to that path and retry the installation.
        If this still fails please open a ticket or create a pull request with a fix on github:
        https://github.com/tcalmant/jpype/

However, I appear to have Java installed into the places it claims to look at.

    $ echo $JAVA_HOME
    /usr/lib/jvm/default-java
    $ namei /usr/bin/java
    f: /usr/bin/java
     d /
     d usr
     d bin
     l java -> /etc/alternatives/java
       d /
       d etc
       d alternatives
       l java -> /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
         d /
         d usr
         d lib
         d jvm
         d java-8-openjdk-amd64
         d jre
         d bin
         - java

Why is Jpype ignoring my installed JDK?

**Comment by chrisspen** [comment]
Nevermind, I didn't realize this project was dead. This bug seems to be fixed in the [parent project](https://github.com/originell/jpype), which installs fine in Python3.

**Comment by tcalmant** [comment]
Hi,
I think the problem is that your Java Home viariable points to a JRE installation, not a JDK one (with C headers and libraries).
The parent project embeds a version of the required header file, which let it compile against a JRE.

But as you said, this fork is dormant.

Cheers,
Thomas

**Comment by tcalmant** [comment]
This project is now deprecated. Please use [jpype-project/jpype](https://github.com/jpype-project/jpype) instead.
