### ISSUE TITLE
Some Error

### ISSUE THREAD

**Issue by ganhb** [tcalmant/jpype-py3#27]
Install success, but there are exceptions when using code
>>>  startJVM(jpype.getDefaultJVMPath())

**Comment by ganhb** [comment]
>>> Traceback (most recent call last):
>>>  File "D:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
>>>    exec(code_obj, self.user_global_ns, self.user_ns)
>>>  File "<ipython-input-6-796a51c94d1d>", line 1, in <module>
>>>    jpype.startJVM(a)
>>>  File "D:\Anaconda\lib\site-packages\jpype\_core.py", line 61, in startJVM
>>>    _jclass._initialize()
>>>  File "D:\Anaconda\lib\site-packages\jpype\_jclass.py", line 43, in _initialize
>>>   _JAVATHROWABLE = JClass("java.lang.Throwable")
>>>  File "D:\Anaconda\lib\site-packages\jpype\_jclass.py", line 59, in JClass
>>>    return _getClassFor(jc)
>>>  File "D:\Anaconda\lib\site-packages\jpype\_jclass.py", line 67, in _getClassFor
>>>    pyJavaClass = _JavaClass(javaClass)
>>>  File "D:\Anaconda\lib\site-packages\jpype\_jclass.py", line 124, in __new__
>>>    bjc = jc.getBaseClass(jc)
>>> TypeError: getBaseClass() takes no arguments (1 given)

**Comment by ganhb** [comment]
Add one,U picture so cool

**Comment by ganhb** [comment]
jpype can call the spring beanfactory it?

**Comment by tcalmant** [comment]
I don't have my computer right now so I can't check it immediately.

How to you intend to create the beanfactory ?

**Comment by ganhb** [comment]
I would like to visit through another jpype to write a java project, access to beanfactory attributes

**Comment by tcalmant** [comment]
Could you provide a small sample of the Java and Python parts ?
I'm not fluent with Spring BeanFactory :/


2018-01-22 7:41 GMT+01:00 agan <notifications@github.com>:

**Comment by ganhb** [comment]
Thank U I have already solved it
